In [1]:
#testing tenserflow library
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.optimizers import RMSprop
import numpy as np
from sklearn.metrics import recall_score
print(tf.__version__)
print(keras.__version__)

2.8.2
2.8.0


In [2]:
import shutil
# 把olddir拷贝一份newdir
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','train')
shutil.copytree('/content/drive/MyDrive/COVID_data_image/validation','validation')

'validation'

In [3]:
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','ag_bc')

'ag_bc'

In [4]:
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','ag_br')

'ag_br'

In [5]:
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','ag_bs')

'ag_bs'

In [6]:
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','ag_rc')

'ag_rc'

In [7]:
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','ag_rs')

'ag_rs'

In [8]:
shutil.copytree('/content/drive/MyDrive/COVID_data_image/train','ag_sc')

'ag_sc'

In [9]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1/255)
validation_datagen = ImageDataGenerator(rescale=1/255)

train_path = '/content/train'
validation_path = '/content/validation'

#class_mode 是多分類
train_generator = train_datagen.flow_from_directory(
    train_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

validation_generator = validation_datagen.flow_from_directory(
    validation_path,
    target_size = (299,299),
    batch_size = 32,
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

Found 12698 images belonging to 4 classes.
Found 4235 images belonging to 4 classes.


In [10]:
#check the label
print(validation_generator.class_indices)

{'COVID': 0, 'Lung_Opacity': 1, 'Normal': 2, 'Viral Pneumonia': 3}


In [11]:
print(train_generator.class_indices)

{'COVID': 0, 'Lung_Opacity': 1, 'Normal': 2, 'Viral Pneumonia': 3}


In [12]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(12, (3,3), activation = 'relu',input_shape = (299,299,3)),
    tf.keras.layers.Conv2D(12, (3,3), activation = 'relu'),
    tf.keras.layers.MaxPool2D(2,2),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Conv2D(24, (3,3), activation = 'relu'),
    tf.keras.layers.Conv2D(48, (3,3), activation = 'relu'),
    tf.keras.layers.Conv2D(64, (3,3), activation = 'relu'),
    tf.keras.layers.MaxPool2D(2,2),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Flatten(),
    
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(4, activation = 'softmax')
])

In [17]:
model.compile(
    loss = 'categorical_crossentropy',
    optimizer = RMSprop(lr=0.001),
    metrics = ['acc']
)

history = model.fit(
    train_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/rmsprop.py:130: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


397/397 [==============================] - 70s 174ms/step - loss: 0.0422 - acc: 0.9887 - val_loss: 1.5518 - val_acc: 0.7986
Epoch 2/15
397/397 [==============================] - 69s 173ms/step - loss: 0.0406 - acc: 0.9893 - val_loss: 1.7785 - val_acc: 0.7913
Epoch 3/15
397/397 [==============================] - 69s 174ms/step - loss: 0.0357 - acc: 0.9905 - val_loss: 1.8125 - val_acc: 0.7936
Epoch 4/15
397/397 [==============================] - 69s 174ms/step - loss: 0.0355 - acc: 0.9911 - val_loss: 1.9276 - val_acc: 0.8017
Epoch 5/15
397/397 [==============================] - 69s 173ms/step - loss: 0.0384 - acc: 0.9915 - val_loss: 2.3943 - val_acc: 0.7809
Epoch 6/15
397/397 [==============================] - 69s 173ms/step - loss: 0.0459 - acc: 0.9895 - val_loss: 2.3238 - val_acc: 0.7936
Epoch 7/15
397/397 [==============================] - 69s 174ms/step - loss: 0.0465 - acc: 0.9901 - val_loss: 2.6596 - val_acc: 0.7865
Epoch 8/15
397/397 [==============================] - 69s 174ms/st

In [18]:
result = model.predict(
    validation_generator
)

In [19]:
predict = result.argmax(axis=1)
predict

array([2, 1, 2, ..., 2, 2, 2])

In [20]:
# (724,1203,2039,269)
target = [0]*724 + [1]*1203 + [2]*2039 + [3]*269
target = np.array(target)
target.shape


(4235,)

In [21]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.3515938606847698


In [22]:
#bc
ag_bc_datagen = ImageDataGenerator(rescale=1/255)

ag_bc_path = '/content/ag_bc'

#class_mode 是多分類
ag_bc_generator = ag_bc_datagen.flow_from_directory(
    ag_bc_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

#br
ag_br_datagen = ImageDataGenerator(rescale=1/255)

ag_br_path = '/content/ag_br'

#class_mode 是多分類
ag_br_generator = ag_br_datagen.flow_from_directory(
    ag_br_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

#bs
ag_bs_datagen = ImageDataGenerator(rescale=1/255)

ag_bs_path = '/content/ag_bs'

#class_mode 是多分類
ag_bs_generator = ag_bs_datagen.flow_from_directory(
    ag_bs_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

#rc
ag_rc_datagen = ImageDataGenerator(rescale=1/255)

ag_rc_path = '/content/ag_rc'

#class_mode 是多分類
ag_rc_generator = ag_rc_datagen.flow_from_directory(
    ag_rc_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

#rs
ag_rs_datagen = ImageDataGenerator(rescale=1/255)

ag_rs_path = '/content/ag_rs'

#class_mode 是多分類
ag_rs_generator = ag_rs_datagen.flow_from_directory(
    ag_rs_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

#sc
ag_sc_datagen = ImageDataGenerator(rescale=1/255)

ag_sc_path = '/content/ag_sc'

#class_mode 是多分類
ag_sc_generator = ag_sc_datagen.flow_from_directory(
    ag_sc_path,
    batch_size = 32,
    target_size = (299,299),
    class_mode='categorical',
    color_mode = 'rgb',
    save_format = 'png'
)

Found 14310 images belonging to 4 classes.
Found 14310 images belonging to 4 classes.
Found 14310 images belonging to 4 classes.
Found 14310 images belonging to 4 classes.
Found 14310 images belonging to 4 classes.
Found 14310 images belonging to 4 classes.


In [23]:
#bc
history = model.fit(
    ag_bc_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15
448/448 [==============================] - 80s 178ms/step - loss: 0.1430 - acc: 0.9889 - val_loss: 2.6655 - val_acc: 0.7646
Epoch 2/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0447 - acc: 0.9916 - val_loss: 3.2931 - val_acc: 0.7809
Epoch 3/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0437 - acc: 0.9926 - val_loss: 3.4405 - val_acc: 0.7674
Epoch 4/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0393 - acc: 0.9930 - val_loss: 3.0213 - val_acc: 0.7913
Epoch 5/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0412 - acc: 0.9932 - val_loss: 2.7330 - val_acc: 0.7577
Epoch 6/15
448/448 [==============================] - 74s 166ms/step - loss: 0.0384 - acc: 0.9933 - val_loss: 2.7272 - val_acc: 0.7792
Epoch 7/15
448/448 [==============================] - 74s 166ms/step - loss: 0.0373 - acc: 0.9929 - val_loss: 2.6855 - val_acc: 0.7941
Epoch 8/15
448/448 [==============================] - 7

In [24]:
result = model.predict(
    validation_generator
)

In [25]:
predict = result.argmax(axis=1)
predict

array([3, 1, 1, ..., 2, 2, 2])

In [ ]:
# (724,1203,2039,269) we do not have to run this block again
# target = [0]*724 + [1]*1203 + [2]*2039 + [3]*269
# target = np.array(target)
# target.shape

In [26]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.3629279811097993


In [27]:
#br
history = model.fit(
    ag_br_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15
448/448 [==============================] - 82s 182ms/step - loss: 0.1898 - acc: 0.9792 - val_loss: 2.6203 - val_acc: 0.7884
Epoch 2/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0437 - acc: 0.9920 - val_loss: 3.1316 - val_acc: 0.7835
Epoch 3/15
448/448 [==============================] - 74s 166ms/step - loss: 0.0549 - acc: 0.9919 - val_loss: 3.4366 - val_acc: 0.7750
Epoch 4/15
448/448 [==============================] - 74s 166ms/step - loss: 0.0416 - acc: 0.9930 - val_loss: 2.6582 - val_acc: 0.7915
Epoch 5/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0390 - acc: 0.9932 - val_loss: 3.1421 - val_acc: 0.7790
Epoch 6/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0407 - acc: 0.9929 - val_loss: 3.6785 - val_acc: 0.7922
Epoch 7/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0390 - acc: 0.9941 - val_loss: 4.0551 - val_acc: 0.7806
Epoch 8/15
448/448 [==============================] - 7

In [28]:
result = model.predict(
    validation_generator
)

In [29]:
predict = result.argmax(axis=1)
predict

array([1, 0, 1, ..., 2, 2, 2])

In [30]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.35489964580873673


In [31]:
#bs
history = model.fit(
    ag_bs_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15
448/448 [==============================] - 81s 180ms/step - loss: 0.0514 - acc: 0.9950 - val_loss: 4.8638 - val_acc: 0.7861
Epoch 2/15
448/448 [==============================] - 73s 163ms/step - loss: 0.0502 - acc: 0.9955 - val_loss: 5.2081 - val_acc: 0.7917
Epoch 3/15
448/448 [==============================] - 73s 164ms/step - loss: 0.0538 - acc: 0.9943 - val_loss: 4.9130 - val_acc: 0.7695
Epoch 4/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0458 - acc: 0.9954 - val_loss: 5.2236 - val_acc: 0.7816
Epoch 5/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0417 - acc: 0.9955 - val_loss: 5.6560 - val_acc: 0.7773
Epoch 6/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0426 - acc: 0.9964 - val_loss: 5.6832 - val_acc: 0.7802
Epoch 7/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0415 - acc: 0.9951 - val_loss: 5.8428 - val_acc: 0.7783
Epoch 8/15
448/448 [==============================] - 7

In [32]:
result = model.predict(
    validation_generator
)

In [33]:
predict = result.argmax(axis=1)
predict

array([2, 2, 2, ..., 2, 0, 2])

In [34]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.35442739079102714


In [35]:
#rc
history = model.fit(
    ag_rc_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15
448/448 [==============================] - 79s 175ms/step - loss: 0.0635 - acc: 0.9948 - val_loss: 8.6212 - val_acc: 0.7752
Epoch 2/15
448/448 [==============================] - 73s 163ms/step - loss: 0.0711 - acc: 0.9945 - val_loss: 7.3082 - val_acc: 0.7884
Epoch 3/15
448/448 [==============================] - 73s 163ms/step - loss: 0.0873 - acc: 0.9943 - val_loss: 6.3988 - val_acc: 0.7948
Epoch 4/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0303 - acc: 0.9964 - val_loss: 6.5456 - val_acc: 0.7877
Epoch 5/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0573 - acc: 0.9950 - val_loss: 8.0645 - val_acc: 0.7948
Epoch 6/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0443 - acc: 0.9961 - val_loss: 6.9203 - val_acc: 0.7972
Epoch 7/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0589 - acc: 0.9955 - val_loss: 7.2402 - val_acc: 0.7891
Epoch 8/15
448/448 [==============================] - 7

In [36]:
result = model.predict(
    validation_generator
)

In [37]:
predict = result.argmax(axis=1)
predict

array([2, 1, 1, ..., 0, 0, 1])

In [38]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.35702479338842974


In [39]:
#rs
history = model.fit(
    ag_rs_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15
448/448 [==============================] - 79s 177ms/step - loss: 0.0544 - acc: 0.9952 - val_loss: 7.6130 - val_acc: 0.7700
Epoch 2/15
448/448 [==============================] - 73s 163ms/step - loss: 0.0528 - acc: 0.9957 - val_loss: 8.1223 - val_acc: 0.7870
Epoch 3/15
448/448 [==============================] - 73s 163ms/step - loss: 0.0412 - acc: 0.9971 - val_loss: 8.0314 - val_acc: 0.7889
Epoch 4/15
448/448 [==============================] - 73s 163ms/step - loss: 0.0572 - acc: 0.9963 - val_loss: 6.8110 - val_acc: 0.7686
Epoch 5/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0454 - acc: 0.9966 - val_loss: 7.8122 - val_acc: 0.7717
Epoch 6/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0495 - acc: 0.9964 - val_loss: 7.8545 - val_acc: 0.7894
Epoch 7/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0467 - acc: 0.9959 - val_loss: 9.1372 - val_acc: 0.7882
Epoch 8/15
448/448 [==============================] - 7

In [40]:
result = model.predict(
    validation_generator
)

In [41]:
predict = result.argmax(axis=1)
predict

array([2, 1, 2, ..., 2, 0, 0])

In [42]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.3624557260920897


In [43]:
#sc
history = model.fit(
    ag_sc_generator,
    epochs = 15,
    verbose = 1,
    validation_data = validation_generator
)

Epoch 1/15
448/448 [==============================] - 80s 178ms/step - loss: 0.0402 - acc: 0.9963 - val_loss: 8.1647 - val_acc: 0.7950
Epoch 2/15
448/448 [==============================] - 75s 167ms/step - loss: 0.0316 - acc: 0.9973 - val_loss: 8.5192 - val_acc: 0.7842
Epoch 3/15
448/448 [==============================] - 74s 166ms/step - loss: 0.0373 - acc: 0.9974 - val_loss: 8.9421 - val_acc: 0.7780
Epoch 4/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0388 - acc: 0.9972 - val_loss: 10.8979 - val_acc: 0.7532
Epoch 5/15
448/448 [==============================] - 74s 165ms/step - loss: 0.0349 - acc: 0.9981 - val_loss: 10.4355 - val_acc: 0.7972
Epoch 6/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0347 - acc: 0.9971 - val_loss: 11.5690 - val_acc: 0.7941
Epoch 7/15
448/448 [==============================] - 74s 164ms/step - loss: 0.0591 - acc: 0.9969 - val_loss: 11.5479 - val_acc: 0.7825
Epoch 8/15
448/448 [==============================]

In [44]:
result = model.predict(
    validation_generator
)

In [45]:
predict = result.argmax(axis=1)
predict

array([1, 2, 0, ..., 2, 2, 3])

In [46]:
labels = [0,1,2,3]
r = recall_score(predict,target,labels=labels, average="micro")

print(r)

0.36363636363636365
